### ISSUE TITLE
missing exp directories crashes JAABA when opened in edit first mode

### ISSUE THREAD

**Issue by arobie** [kristinbranson/JAABA#289]
When you start a classifier in the "edit" first mode, it does not properly handle missing experiments directories. It just crashes rather than asking to locate files.

**Comment by allenleetc** [comment]
Alice, can you help me understand what you/others use edit mode for? Like typically what aspects of a project are chnaged when you use this option? Currently, it looks like other bad things can happen when edit mode is used, eg if you change the classifier/behavior name, labels get corrupted because they are not updated (they keep the original behavior name) etc.

**Comment by arobie** [comment]
Usually if I mess up something like target type, tracking file name or
movie file name, its really obvious early on and I just start a new
classifier. So I'm not sure if I've ever changed those is an existing jab
file with labels, etc.

I have definitely used the edit-> advanced options to add parameters to
older classifiers and to add/remove perframe features, since those can't be
edited within JAABA.

Both behavior name and score file name can be changed in the JAABA GUI, do
those changes work properly?

I think we generally treated importing labels and exps to a new jab file as
a cleaner way to change major back-end pieces of the classifier. Doing it
that way, I think importing has to match the behavior name between old and
new.

-Alice

**Comment by kristinbranson** [comment]
I don't think I've ever used the edit function.

KB

**Comment by kristinbranson** [comment]
I agree that removing broken functionality is a good idea.

**Comment by allenleetc** [comment]
OK, thanks for the info. Yes changing the behavior name(s) and scorefile name(s) in the main UI should work. I will probably just disable any broken aspects of Edit mode (it might just be changing the behavior/classifier name). Otherwise I think the main issue reported here can be addressed by a merge of the internal methods JLabelData:openJabFile and newJabFile.

**Comment by allenleetc** [comment]
After digging a little more I am suspicious again. I think editing the PFF list in Edit mode is currently broken and potentially dangerous. I can see it maybe working if you do the right things after the project opens, but in today's code eg if you just reduce the PFF list and naively hit Play or Predict you get an opaque error; for good reason, because the project is in a corrupt state I believe. 

I went through all the things you can potentially change in Edit mode and the status of them is below. Basically, you have i) filenames (trx, movie, etc), ii) cosmetic things like graphics colors, and iii) the "extra" parameters. The first two are probably OK, I am not sure about the third.

Any thoughts welcome, by default I'll just remove/disable stuff.

LIST OF EDITABLE PROJECT STUFF
* Main Window
  * BehaviorName -- BROKEN, functionality covered under File> menu
  * Tracking Data File Name -- prob OK
  * Movie Filename -- prob OK
  * Score Filename -- prob OK, covered under File> menu
* Advanced
  * Choose PFF button -- BROKEN, dangerous
  * featureLexiconName -- presumably disallow
  * behaviors.type -- presumably disallow
  * behaviors.labelcolors -- prob OK
  * behaviors.unknowncolor -- prob OK
  * file.clipsdir -- prob OK
  * file.perframedir -- NOT SURE IF OK
  * trxGraphicParams.* -- prob OK
  * labelGraphicParams.* -- LOOKS UNUSED BY ANYTHING remove
  * extra.perframe.landmarkParams.* -- NOT SURE
  * extra.perframe.params.* -- NOT SURE

**Comment by allenleetc** [comment]
I disabled the aspects of Edit mode that I could figure out were unsafe. There's not that much left and it might defeat the purpose to some extent.
