### ISSUE TITLE
Export/import single classifiers from/into a multiclassifier jab file

### ISSUE THREAD

**Issue by mkabra** [kristinbranson/JAABA#296]

**Comment by allenleetc** [comment]
There is a command-line utility related to this in Macguffin (jabMerge, untested in integration branch and probably slightly stale), but it doesn't cover all use cases. This type of operation seems pretty useful and I am thinking it is worth adding functionality under the File> menu. 

*Mini-spec*, supported JAABA operations for Classifier management. For probable addition under the File> menu (eg in a submenu):

* Remove a single classifier from an existing project.
* Add a new "blank" classifier to an existing project.
* Reorder classifiers in an existing project.
* Rename classifiers -- _already supported_.
* Import existing experiments/labels from an existing Jab, merging into a classifier in the current project. This operation already exists for single-classifier projects. The only change for multi-classifier source/target projects is that the user must select the source/target classifier(s).
* Import existing experiments/labels/classifier from an existing Jab, augmenting current project. This adds a new classifier to the current project.

A useful side-effect of these changes might be to improve support for experimentation/comparison of multiple versions of a single classifier(?).

**Comment by allenleetc** [comment]
The "online" classifier management features turned out to be a pain to implement. I put in Add/Rm and those are probably pretty solid, but in the long run they feel fragile and high maintenance due to complexity and scattered support from underlying organization/APIs. Given this I am punting on the full "online" support and closing this issue. The original suggestion has been moved to #308 and that should be much easier/robust to implement; it is probably also more to the point for a power-user.

A side benefit of the online implementation was a bunch of cleanup of JLabel/JLabelGUIData.
