### ISSUE TITLE
Issue on trk.file produced by APT

### ISSUE THREAD

**Issue by Junes94** [kristinbranson/JAABA#333]
Hi, I faced some difficulties in generating features using JAABA from .trk file produced by APT.
And I got the error window as screenshots.
 I've done all procedures as manual said, but don't know the reason there is an error in adding expdir.
The error windows said that the .trk file has different number of column between first and second column.
 
Did I do wrong when exporting .trk file from APT project?
I used .avi movie file and mdn training(local conda) for tracking just one landmark. And after training, I just tracked all frames and then saved the project to .lbl file and export the tracking results to .trk file. And I used 'MATLAB R2019.a'

Thank you.

![JAABA_1](https://user-images.githubusercontent.com/64457340/80451567-22fb1480-895f-11ea-91b5-24c0c3e078ef.png)
![JAABA_2](https://user-images.githubusercontent.com/64457340/80451571-242c4180-895f-11ea-87d9-f268349ed325.png)
![JAABA_3](https://user-images.githubusercontent.com/64457340/80451573-242c4180-895f-11ea-8676-314e7259e07f.png)
![JAABA_4](https://user-images.githubusercontent.com/64457340/80451574-24c4d800-895f-11ea-9ade-393e24c7958c.png)
![JAABA_5](https://user-images.githubusercontent.com/64457340/80451575-24c4d800-895f-11ea-831b-cbe0aeea1eda.png)

**Comment by mkabra** [comment]
Hi,

In the "New JAABA Project" window, the "Tracking Data File Name" refers to
a trx file that is different than a trk file. The trx file has animal
tracking data such as centroid and orientation typically generated by CTrax
or other whole animal trackers. Since this file is essential for JAABA and
not all APT projects might have them, when creating projects from APT we
give an option to automatically create one. This is the "For JAABA Trx
use..." option in APTProject window. In this case, the file name specified
in "Tracking Data File Name" in the "New JAABA Project Window" is where
this automatically created file is stored. So you should specify something
like "tracks.trx" or "fr_1.trx".

Also, note that that JAABA needs a separate directory for each movie and
the movie files that you would like to use should have the same name. Eg,
if you specify the "Movie File Name" as fr_1.avi, then you won't be able to
see fr_2.avi in JAABA unless you move it to a different directory and
rename it as fr_1.avi. The same goes for the trk file as well.

Mayank

**Comment by JuneJuly94** [comment]
Dear Mayank
Thank you for your reply and kindness.
I misunderstood that trk file already has animal tracking data.
And your notation also would be helpful.

However, even though the .trx file is made in the directory folder, it still doesn't work and there is a same error as shown 4th, 5th screenshots above.

**Comment by mkabra** [comment]
Can you load the trk file in matlab using the load command? Eg.
load('/path/to/trk_file','-mat'). If yes, can you send the trx and the trk
files?

Mayank

**Comment by JuneJuly94** [comment]
I could load it, so I send you files.
thank you

best regards,

2020년 4월 28일 (화) 오후 8:11, mkabra <notifications@github.com>님이 작성:

> Can you load the trk file in matlab using the load command? Eg.
> load('/path/to/trk_file','-mat'). If yes, can you send the trx and the trk
> files?
>
> Mayank
>
>

**Comment by JuneJuly94** [comment]
I could load it in MATLAB, so I send you files.
Thank you

June

[fr_pilot.zip](https://github.com/kristinbranson/JAABA/files/4545365/fr_pilot.zip)

**Comment by mkabra** [comment]
Yeah, the trk and trx file are fine and I was able to create the JAABA
project based on the trk and trx file.

While looking at the screenshots, I see that you defined a custom perframe
feature "fr" in APTProject. If you do that, then you need to make sure that
there exists a file fr.mat in perframe directory before you add that
experiment to JAABA. The custom perframe features are the ones that you
want to create using your own code. So as a test, I suggest not giving
anything in custom perframe feature list and try again.

Mayank

**Comment by JuneJuly94** [comment]
Dear Mayank,
I just left the custom perframe feature blank, but still have a same error.

**Comment by mkabra** [comment]
Can you check if it still errors if you use frame center instead of crop
center for generating the trx file?

Mayank

**Comment by JuneJuly94** [comment]
Yes, the same error windows still pops up.

**Comment by mkabra** [comment]
Hmm. Did you try restarting Matlab? And if you still see the error, can you
send me the APT project file and the video?

Mayank

**Comment by JuneJuly94** [comment]
Yes, I always restarted Matlab,
Here's the link of my files and video.

https://drive.google.com/file/d/1B7Ab8f9ASURmOUZMCzip4PraL6_zqAqn/view?usp=sharing

Thank you.

**Comment by mkabra** [comment]
Hi,

So yeah there was a bug in JAABA that required the trx file to end with
.mat. If you pull the latest version of JAABA, you should be able to create
the project in JAABA.

Mayank

**Comment by JuneJuly94** [comment]
Hi,

I'm glad it works well now.
Thank you very much, have a good one !

June
